<a href="https://colab.research.google.com/github/PedroHS05/am-t4-s1a2026/blob/main/Aula0428API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import requests
import pandas as pd

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&interval=5min&apikey=J6MPIRJ7Y8YSVBUH'
r = requests.get(url)
base = r.json()

In [6]:
base_alpha = pd.DataFrame.from_dict(base['Time Series (Daily)'], orient='index')
base_alpha - base_alpha.transpose()
base_alpha

             1. open   2. high    3. low  4. close 5. volume
2026-04-27  229.9500  231.3200  227.1200  228.0500   8060665
2026-04-24  231.9300  232.7999  225.0000  231.9800   9816859
2026-04-23  232.2700  232.9100  221.7300  231.0800  22297831
2026-04-22  254.5100  257.5400  247.2100  251.8600  12190197
2026-04-21  254.0000  258.0900  251.8650  255.6800   5584901
...              ...       ...       ...       ...       ...
2025-12-08  309.6200  315.3454  307.9500  309.1800   3615794
2025-12-05  308.5900  311.8300  307.1800  307.9400   2344667
2025-12-04  302.8750  309.6100  302.5400  307.9900   2962463
2025-12-03  302.8800  303.9700  298.9050  302.6200   3953390
2025-12-02  307.0000  310.4675  301.5700  301.7800   4261100

[100 rows x 5 columns]

In [32]:
base_alpha = base_alpha.T

In [33]:
base_alpha

             1. open   2. high    3. low  4. close 5. volume
2026-04-27  229.9500  231.3200  227.1200  228.0500   8060665
2026-04-24  231.9300  232.7999  225.0000  231.9800   9816859
2026-04-23  232.2700  232.9100  221.7300  231.0800  22297831
2026-04-22  254.5100  257.5400  247.2100  251.8600  12190197
2026-04-21  254.0000  258.0900  251.8650  255.6800   5584901
...              ...       ...       ...       ...       ...
2025-12-08  309.6200  315.3454  307.9500  309.1800   3615794
2025-12-05  308.5900  311.8300  307.1800  307.9400   2344667
2025-12-04  302.8750  309.6100  302.5400  307.9900   2962463
2025-12-03  302.8800  303.9700  298.9050  302.6200   3953390
2025-12-02  307.0000  310.4675  301.5700  301.7800   4261100

[100 rows x 5 columns]

In [34]:
import numpy as np

In [35]:
base_alpha_num = base_alpha.astype(float)

In [36]:
base_alpha_num['target'] = (base_alpha_num['4. close'].shift(-1) > base_alpha_num['4. close'])
base_alpha_num.dropna(inplace=True)